# Generated by Django 5.2.12 on 2026-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0002_product_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
