# Generated by Django 5.2.12 on 2026-04-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myecommerce', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
